### ISSUE TITLE
Create selectMentor() method

### ISSUE THREAD

**Issue by bahati2000** [bahati2000/expertiza#1]

**Comment by AvlWx2014** [comment]
@molinamelendezj @bahati2000 @Hatsukikeika - thinking about adding a class called `MentorManagement` to handle this specific set of logic. Probably through class methods like

```ruby
class MentorManagement
  def self.select_mentor()
    # TODO
  end

  private 

  def self.get_all_mentors()
    # TODO
  end

  def self.zip_mentors_with_mentee_count()
    # TODO
  end 
end
```

Thoughts?

**Comment by bahati2000** [comment]
Will the Class also be responsible for removing mentor or sending emails?
