### ISSUE TITLE
Create Main logic and trigger

### ISSUE THREAD

**Issue by molinamelendezj** [bahati2000/expertiza#5]
**What needs to be done**
Develop a trigger that:

- Is activated when any team has been formed that has k members, where k is greater than 50% of the maximum team capacity
- ex: max members = 4, trigger activated when the team size reaches 3
- Assign a mentor to the team
- Mentors should be evenly assigned to teams, so a good strategy is to assign the mentor who has the fewest teams to mentor so far.
- Notify the mentor via email that they are now assigned to a specific team, and provide the email addresses of the team members.
- Possibly notify the team members that they have been assigned the mentor with contact information (further discussion here).
- Preconditions
- The mentor assignment feature has a few preconditions and assumptions which have been outlined below.

An instructor has already added an assignment without topics.
“mentor” permission exist
There are users in said assignment with mentor permissions.
A mentor has yet to be assigned to said assignment.
Mentor assignment is done only once, does not take into consideration drop offs.

**Comment by molinamelendezj** [comment]
@bahati2000, @Hatsukikeika , @AvlWx2014 You guys think putting the "trigger" after the `accept` logic has run is a good place?

https://github.com/bahati2000/expertiza/blob/69d9702243e650f0e055588a3897d28efb28a64b/app/controllers/invitations_controller.rb#L46-L53

**Comment by AvlWx2014** [comment]
I'm not sure this is the place for it. Maybe in `assignment_team.rb`?

**Comment by molinamelendezj** [comment]
Ok let me take a look in there too.

**Comment by AvlWx2014** [comment]
`Invitation#accept_invite` calls `TeamsUser#add_member_to_invited_team`, which in turn calls `Team#add_member`, which is not overridden by `AssignmentTeam`. So I suppose the code would end up in `team.rb`.

**Comment by molinamelendezj** [comment]
Yea, and I thought he didn't want it there? So that is why I was trying to call it up front to a new `.rb` class we create. We'll let me try couple things and if he doesn't like it there he can tell us Thursday  😄
